ExpenseManagerDemo/Controllers/ExpenseController.cs
using ExpenseManagerDataAccesLibrary;
using ExpenseManagerDataAccesLibrary.Interfaces;
using ExpenseManagerDataAccesLibrary.Models;
using ExpenseManagerDataAccesLibrary.Repositories;
using ExpenseManagerDemo.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExpenseManagerDemo.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly IExpenseRepository expenseRepository = new ExpenseRepository();

        // GET: Expense
        [Authorize]
        public ActionResult Index(string sort, DateTime? dateFrom, DateTime? dateTo, int? categoryId)
        {
            if(dateFrom != null && dateTo != null)
            {
                ViewBag.DateFrom = dateFrom;
                ViewBag.DateTo = dateTo;
            }
            ViewBag.Sort = "desc";
            ViewBag.Sort = !String.IsNullOrEmpty(sort)&& sort=="asc" ? "desc" : "asc";
            ViewBag.ExpenseCategories = ExpenseRepository.Categories;

            IEnumerable<Expenses> expenses = expenseRepository.GetAllExpensesByUser(User.Identity.GetUserId(), dateFrom, dateTo, categoryId, sort);
            List<ExpenseViewModel> expenseViewModel = new List<ExpenseViewModel>();
            foreach(var item in expenses)
            {
                var viewModelItem = new ExpenseViewModel
                {
                    Id = item.Id,
                    Category = expenseRepository.GetCategoryNameById(item.CategoryId),
                    Date = item.Date,
                    Name = item.Name,
                    Value = item.Value
                };

                expenseViewModel.Add(viewModelItem);
            }
            return View(expenseViewModel);
        }

        [Authorize]
        public ActionResult AddExpense()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddExpense(Expenses expenses)
        {
            expenses.UserId = User.Identity.GetUserId();
            expenseRepository.AddExpense(expenses);
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            expenseRepository.RemoveExpense(id);

            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult EditExpense (int id)
        {
            var expense = expenseRepository.GetExpenseById(id);

            return View(expense);

        }
        [HttpPost]
        [Authorize]
        public ActionResult EditExpense(Expenses expenses)
        {
            expenses.UserId = User.Identity.GetUserId();
            expenseRepository.UpdateExpense(expenses);

            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddCategory (ExpenseCategories expenseCategories)
        {
            expenseRepository.AddExpenseCategory(expenseCategories);
            return RedirectToAction("AddExpense");
        }
    }
}

ExpenseManagerDemo/Controllers/IncomeController.cs
using ExpenseManagerDataAccesLibrary.Models;
using ExpenseManagerDataAccesLibrary.Repositories;
using ExpenseManagerDemo.Models;
using ExpenseManagerDataAccesLibrary.Repositories;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExpenseManagerDataAccesLibrary.Interfaces;

namespace ExpenseManagerDemo.Controllers
{
    public class IncomeController : Controller
    {
        private readonly IIncomeRepository incomeRepository = new IncomeRepository();

        // GET: Income
        [Authorize]
        public ActionResult Index(string sort, DateTime? dateFrom, DateTime? dateTo, int? categoryId)
        {
            if (dateFrom != null && dateTo != null)
            {
                ViewBag.DateFrom = dateFrom;
                ViewBag.DateTo = dateTo;
            }
            ViewBag.Sort = "desc";
            ViewBag.Sort = !String.IsNullOrEmpty(sort) && sort == "asc" ? "desc" : "asc";
            ViewBag.IncomeCategories = IncomeRepository.Categories;

            IEnumerable<Incomes> incomes = incomeRepository.GetAllIncomesByUser(User.Identity.GetUserId(), dateFrom, dateTo, categoryId, sort);
            List<IncomeViewModel> incomeViewModel = new List<IncomeViewModel>();
            foreach (var item in incomes)
            {
                var viewModelItem = new IncomeViewModel
                {
                    Id = item.Id,
                    Category = incomeRepository.GetCategoryNameById(item.CategoryId),
                    Date = item.Date,
                    Name = item.Name,
                    Value = item.Value
                };

                incomeViewModel.Add(viewModelItem);
            }
            return View(incomeViewModel);
        }

        [Authorize]
        public ActionResult AddIncome()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddIncome(Incomes incomes)
        {
            incomes.UserId = User.Identity.GetUserId();
            incomeRepository.AddIncome(incomes);
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult EditIncome(int id)
        {
            var income = incomeRepository.GetIncomeById(id);

            return View(income);

        }
        [HttpPost]
        [Authorize]
        public ActionResult EditIncome(Incomes incomes)
        {
            incomes.UserId = User.Identity.GetUserId();
            incomeRepository.UpdateIncome(incomes);

            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult AddCategory()
        {
            return View();
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            incomeRepository.RemoveIncome(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddCategory(IncomeCategories incomeCategories)
        {
            incomeRepository.AddIncomeCategory(incomeCategories);
            return RedirectToAction("AddIncome");
        }
    }
}

ExpenseManagerDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" >
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav mr-auto">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Expenses", "Index", "Expense")</li>
                    <li>@Html.ActionLink("Add Expense", "AddExpense", "Expense")</li>
                    <li>@Html.ActionLink("Incomes", "Index", "Income")</li>
                    <li>@Html.ActionLink("Add Income", "AddIncome", "Income")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
</body>
</html>